# fly.toml app configuration file generated for sua-api-investimentos
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'sua-api-investimentos'
primary_region = 'gru' # São Paulo - mais próximo do Brasil

[build]

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://0.0.0.0:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # IMPORTANTE: Impede hibernação
  auto_start_machines = true
  min_machines_running = 1   # IMPORTANTE: Mantém pelo menos 1 máquina sempre rodando

  # Health check
  [http_service.checks]
    [http_service.checks.health]
      grace_period = '30s'
      interval = '15s'
      method = 'GET'
      path = '/swagger'
      timeout = '10s'
      type = 'http'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Configuração para evitar hibernação
[experimental]
  auto_rollback = true